version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8.4

    steps:
      - run:
          name: "Install pybiolib"
          command: pip3 install pybiolib

      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: "Build Docker Image"
          command: docker build -t rfdesign . -f docker/Dockerfile

      - run:
          name : biolib push rfdesign
          command: biolib push DTU-Bioengineering/RFDesign

workflows:
  build:
    jobs:
      - build:
          context:
            - BIOLIB_TOKEN
