biolib_version: 2
modules:
  main:
    image: 'local-docker://rfdesign:latest'
    command: 'bash /root/RFDesign/biolib_run.sh'
    input_files:
      - COPY / /
    output_files: 
      - COPY /output/ /
    default_machine: 'gpu.small'
    
arguments: []
